"""Generate static Sphinx pages from the installed pybind11 extension.

The generated files are ordinary RST, so subsequent documentation builds do
not import DEME or require a CUDA-capable documentation host.
"""

from __future__ import annotations

import argparse
import importlib
import inspect
from pathlib import Path
from types import ModuleType


def indent(text: str, spaces: int = 3) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else "" for line in text.splitlines())


def public_members(value: object) -> list[tuple[str, object]]:
    """Return stable, public members defined by a module or bound class."""
    return sorted(
        (
            (name, member)
            for name, member in vars(value).items()
            if not name.startswith("_") and name not in {"name", "value"}
        ),
        key=lambda item: item[0].lower(),
    )


def clean_doc(value: object, fallback: str) -> str:
    return inspect.getdoc(value) or fallback


def render_doc(value: object, fallback: str) -> str:
    """Render arbitrary pybind text literally so signatures cannot become RST."""
    return f"   .. code-block:: text\n\n{indent(clean_doc(value, fallback), 6)}"


def render_function(name: str, value: object, owner: str | None = None) -> str:
    directive = "method" if owner else "function"
    qualified = f"{owner}.{name}" if owner else name
    return (
        f".. py:{directive}:: {qualified}\n\n"
        f"{render_doc(value, 'No description is currently available.')}\n"
    )


def render_class(name: str, value: type) -> str:
    lines = [
        name,
        "-" * len(name),
        "",
        f".. py:class:: {name}",
        "",
        render_doc(value, "No class description is currently available."),
        "",
    ]

    # Dunder methods are omitted from the general member list, but the
    # constructor is fundamental API documentation and belongs first.
    constructor = vars(value).get("__init__")
    if constructor is not None:
        lines.extend([render_function("__init__", constructor, name), ""])

    for member_name, member in public_members(value):
        if callable(member):
            lines.extend([render_function(member_name, member, name), ""])
        elif not inspect.isclass(member):
            lines.extend(
                [
                    f".. py:attribute:: {name}.{member_name}",
                    "",
                    render_doc(member, "Bound attribute."),
                    "",
                ]
            )
    return "\n".join(lines)


def generate(module: ModuleType, output: Path) -> None:
    """Write one deterministic reference document for a bound module."""
    title = f"Python API reference: ``{module.__name__}``"
    lines = [
        title,
        "=" * len(title),
        "",
        ".. This file is generated by docs/generate_python_reference.py.",
        ".. Do not edit it directly; improve the pybind11 docstring and regenerate.",
        "",
        "This reference is generated from the signatures and docstrings exposed by",
        f"the installed ``{module.__name__}`` extension.",
        "",
    ]

    functions: list[tuple[str, object]] = []
    classes: list[tuple[str, type]] = []
    for name, value in public_members(module):
        if inspect.isclass(value) and getattr(value, "__module__", "").split(".")[-1] in {
            module.__name__.split(".")[-1],
            "_deme",
        }:
            classes.append((name, value))
        elif inspect.isbuiltin(value) or inspect.isfunction(value):
            functions.append((name, value))

    if functions:
        lines.extend(["Module functions", "----------------", ""])
        for name, value in functions:
            lines.extend([render_function(name, value), ""])

    if classes:
        # Put the main user entry points before supporting types and enums.
        class_priority = {"DEMSolver": 0, "DEMVisualizer": 1, "Tracker": 2}
        classes.sort(key=lambda item: (class_priority.get(item[0], 2), item[0].lower()))
        lines.extend(["Classes", "-------", ""])
        for name, value in classes:
            lines.extend([render_class(name, value), ""])

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--module", default="deme", help="Installed module to inspect")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).parent / "python" / "reference.rst",
        help="RST file to write",
    )
    args = parser.parse_args()
    generate(importlib.import_module(args.module), args.output)


if __name__ == "__main__":
    main()
